Repository llbllhllk/project_to-do-mate, pull requests merged in 2022-01, with the labels that each got.

#18 Tab button관련 publishing수정 및 JS작성
  assets/images/tab-delete-button.png
  assets/javascripts/main.js
  assets/styles/header.css
  assets/styles/tab.css
  pages/main.html
Labels: fix, JS

#9 Feat: Sign up 관련 html, css 수정
  assets/styles/sign-up.css
  pages/sign-up.html
Labels: publishing, fix

#20 friend page에 대한 publishing 및 로그인 수정
  assets/styles/friend.css
  pages/friend.html
  pages/login.html
Labels: publishing, fix

#22 Sign up, Tab, Login관련 css 수정
  assets/styles/header.css
  assets/styles/sign-up.css
  assets/styles/tab.css
  pages/login.html
  pages/sign-up.html
Labels: fix
